docker:
  default:
    image: svirlyu/comapr_dev

  stages:
    - build
    - document
    - check
    - test
    - deploy

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  CODECOV_TOKEN: "2329aed3-de38-468c-9a06-95564363211c"
  GIT_SSL_NO_VERIFY: "true"

before_script:

buildbinary:
  image: svirlyu/comapr_dev
  stage: build
  script:
    - R -e 'devtools::build(binary = TRUE)'

documentation:
  image: svirlyu/comapr_dev
  stage: document
  script:
    - R -e 'devtools::document()'

checkerrors:
  image: svirlyu/comapr_dev  
  stage: check
  script:
    - R -e 'if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["errors"]], character(0))) stop("Check with Errors")'

checkwarnings:
  stage: check
  script:
    - R -e 'if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["warnings"]], character(0))) stop("Check with Warnings")'

checknotes:
  stage: check
  script:
    - R -e 'if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["notes"]], character(0))) stop("Check with Notes")'

unittests:
  stage: test
  script:
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'

codecov:
  stage: test
  script:
    - R -e 'covr::codecov()'

install:
  stage: deploy
  script:
    - R -e 'devtools::install()'
